---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mattermost
  namespace: istio-system
spec:
  hosts:
  - mattermost-bpaulson-replace.platform1.ninja
  gateways:
  - istio-gateway
  http:
    - route:
      - destination:
          host: mattermost-team-edition.mattermost.svc.cluster.local
          port:
            number: 8065

